### ISSUE TITLE
Failed to initialize config in mattermost load-test

### ISSUE THREAD

**Issue by sourabkumarkeshri** [mattermost/mattermost-load-test#160]
I am trying to run mattermost load-test locally.I am done with the setup.
The profiling strategy I used is manual loadtesting against an existing cluster.

When I run the "loadtest all" command,I get the following error.

{“level”:“error”,“msg”:“Failed to initialize config”,“fields”:[{“Key”:“error”,“Type”:25,“Integer”:0,“String”:"",“Interface”:{}}]}

As per the instructions,I copied the default loadtestconfig.json and made changes in the “MattermostInstallDir” field as required.But,I am not sure what do I need to put in other fields.If someone can share their “loadtestconfig.json” . file . or help me with the issue,it would be great.

**Comment by reflog** [comment]
@sourabkumarkeshri - can you attach your “loadtestconfig.json” file? (please replace any sensitive information like passwords and URLs before pasting) We'll try to see what the issue is

**Comment by sourabkumarkeshri** [comment]
Here is my loadtestconfig.json file.I have made changes only in Connection Configuration and nowhere else.

[loadtestconfig.txt](https://github.com/mattermost/mattermost-load-test/files/3446082/loadtestconfig.txt)

**Comment by reflog** [comment]
@sourabkumarkeshri - thanks. The file is missing an opening bracket. Can you check please?
![image](https://user-images.githubusercontent.com/109876/62122518-8cfe6480-b2ce-11e9-926a-f3bb38ba63e9.png)

**Comment by sourabkumarkeshri** [comment]
Thanks @reflog. That worked.

**Comment by reflog** [comment]
Glad that helped!
